//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReceipt
    {
        public string Id { get; set; }
        public int ProductId { get; set; }
        public decimal ImportPrice { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string StaffId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
