//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatSetting
    {
        public int SeatId { get; set; }
        public int ShowtimeId { get; set; }
        public bool Status { get; set; }
    
        public virtual Seat Seat { get; set; }
        public virtual Showtime Showtime { get; set; }
    }
}
