//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketBillInfo
    {
        public int BillId { get; set; }
        public int TicketId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
