//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string VoucherReleaseId { get; set; }
        public string Status { get; set; }
        public string CustomerId { get; set; }
        public Nullable<System.DateTime> UsedAt { get; set; }
        public Nullable<System.DateTime> ReleaseAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual VoucherRelease VoucherRelease { get; set; }
    }
}
