Create DATABASE CinemaManagement

use CinemaManagement


SET DATEFORMAT dmy


--TABLE STAFF
CREATE TABLE Staff(
	Id INT IDENTITY(1,1),
	Name nvarchar(50) NOT NULL,
	Username varchar(50),
	Password nvarchar(100),
	PhoneNumber varchar(20) NOT NULL,
	Age INT,
	BirthDate SMALLDATETIME,
	Gender nchar(3) NOT NULL,
	StartingDate SMALLDATETIME DEFAULT CONVERT(VARCHAR(10), GETDATE(), 103),
	Role nvarchar(20) DEFAULT 'Nhân viên',

	CONSTRAINT PK_STAFF PRIMARY KEY (Id),
	CONSTRAINT CHECK_STAFF CHECK (Age>=12 AND Role IN (N'Nhân viên', N'Quản lý') AND Gender IN (N'Nam', N'Nữ')),
);

SELECT * FROM Staff;




--TABLE Customer
 
CREATE TABLE Customer(
	Id INT IDENTITY(1,1),
	Name  nvarchar(50) NOT NULL,
	PhoneNumber varchar(20) NOT NULL UNIQUE,

	CONSTRAINT PK_Customer PRIMARY KEY (Id),
)

 
CREATE TABLE Genre(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	DisplayName nvarchar(50) NOT NULL UNIQUE
)

 
CREATE TABLE Movie(
	Id INT IDENTITY(1,1), 
	DisplayName nvarchar(200) NOT NULL UNIQUE, 
	RunningTime INT NOT NULL,  
	Country nvarchar(50),
	Description nvarchar(max),
	 ReleaseDate SMALLDATETIME,
	MovieType nvarchar(50) DEFAULT '2D',
	Director nvarchar(200) NOT NULL,

	CONSTRAINT PK_MOVIE PRIMARY KEY (Id),
	CONSTRAINT MOVIE_TYPE_CHECK CHECK(MovieType IN ('2D', '3D')),
)

CREATE TABLE GenreDetails(
	GenreId INT,
	MovieId INT,

	CONSTRAINT PK_GENREDETAILS PRIMARY KEY (GenreId, MovieId),
	CONSTRAINT GENREID_FK FOREIGN KEY (GenreId) REFERENCES Genre(Id),
	CONSTRAINT MOVIEID_FK FOREIGN KEY (MovieId) REFERENCES Movie(Id),
)

CREATE TABLE Product(
	Id INT IDENTITY(1,1),
	DisplayName nvarchar(50) NOT NULL,
	Category nvarchar(20),
	Price MONEY NOT NULL,  

	CONSTRAINT PK_PRODUCT PRIMARY KEY (Id),
	CONSTRAINT CATEGORY_CHECK CHECK(Category IN ('Đồ ăn', 'Nước uống')),
)



CREATE TABLE Room(

	Id INT IDENTITY(1,1),
	SeatAmount INT NOT NULL DEFAULT 50,  

	CONSTRAINT PK_ROOM PRIMARY KEY (Id),
)




CREATE TABLE Seat(
	Id INT IDENTITY(1,1),
	SeatNumber INT NOT NULL,  
	Row char(1) NOT NULL,  
	RoomId INT,
	CONSTRAINT PK_SEAT PRIMARY KEY (Id),
	UNIQUE(Row, SeatNumber, RoomId),
	CONSTRAINT ROOMID_SEAT_FK FOREIGN KEY (RoomId) REFERENCES Room(Id)
)


CREATE TABLE ShowtimeSetting(

	Id INT IDENTITY(1,1),
	ShowDate DATETIME NOT NULL,  
	RoomId INT,

	CONSTRAINT PK_SHOWTIMESETTING PRIMARY KEY (Id),
	UNIQUE(ShowDate, RoomId),
	CONSTRAINT ROOMID_SETTINGSHOWTIME_FK FOREIGN KEY (RoomId) REFERENCES Room(Id)
)


CREATE TABLE Showtime(
	Id INT IDENTITY(1,1),
	ShowtimeSettingId INT,
	MovieId INT,
	StartTime TIME,


	CONSTRAINT PK_SHOWTIME PRIMARY KEY (Id),
	FOREIGN KEY (MovieId) REFERENCES Movie(Id),
	FOREIGN KEY (ShowtimeSettingId) REFERENCES ShowtimeSetting(Id)
)



CREATE TABLE SeatSetting(
	SeatId INT NOT NULL,
	ShowtimeId INT NOT NULL,
	Status BIT NOT NULL DEFAULT(0)

	CONSTRAINT PK_SEATSETTING PRIMARY KEY (SeatId,ShowtimeId),
	FOREIGN KEY (SeatId) REFERENCES Seat(Id),
	FOREIGN KEY (ShowtimeId) REFERENCES Showtime(Id)
)


CREATE TABLE Ticket(
	Id INT IDENTITY(1,1),
	ShowtimeId INT NOT NULL, 
	SeatId INT NOT NULL,  
	Price MONEY NOT NULL DEFAULT 45000 CHECK (Price > 0),

	CONSTRAINT PK_TICKET PRIMARY KEY (Id),
	FOREIGN KEY (SeatId) REFERENCES Seat(Id),
	FOREIGN KEY (ShowtimeId) REFERENCES Showtime(Id)
)

CREATE TABLE Bill(
	Id INT IDENTITY(1,1),
	CustomerId INT NOT NULL,
	StaffId INT,
	CreatedAt DATETIME DEFAULT GETDATE(),
	TotalPrice MONEY NOT NULL,


	CONSTRAINT PK_BILL PRIMARY KEY (Id),
	FOREIGN KEY (CustomerId) REFERENCES Customer(Id),
	FOREIGN KEY (StaffId) REFERENCES Staff(Id)
)


CREATE TABLE ProductBillInfo(
	BillId INT  NOT NULL,
	ProductId INT NOT NULL,
	Amount INT DEFAULT(1) CHECK (Amount > 0),
	PricePerItem MONEY NOT NULL CHECK (PricePerItem > 0),

	CONSTRAINT PK_PRODUCTBILL PRIMARY KEY (BillId, ProductId),
	FOREIGN KEY (BillId) REFERENCES Bill(Id),
	FOREIGN KEY (ProductId) REFERENCES Product(Id)
)


CREATE TABLE TicketBillInfo(
	BillId INT NOT NULL,
	TicketId INT NOT NULL,
	Price MONEY NOT NULL CHECK (Price > 0)


	CONSTRAINT PK_TICKETBILL PRIMARY KEY (BillId, TicketId),
	FOREIGN KEY (BillId) REFERENCES Bill(Id),
	FOREIGN KEY (TicketId) REFERENCES Ticket(Id)
)